import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
 
/**
 * @author DiscoDurodeRoer
 */
public class verRuta extends javax.swing.JFrame {
 
    /**
     * Creates new form RutaArchivoApp
     */
    public verRuta() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
 
        txtRuta = new javax.swing.JTextField();
        btnElegir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar ruta fichero");
 
        txtRuta.setEditable(false);
 
        btnElegir.setText("...");
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
 
        jLabel1.setText("Pulsa el boton");
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(43)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(txtRuta, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(btnElegir, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(49)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtRuta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnElegir))
        			.addContainerGap(44, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
 
        pack();
    }                      
 
    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {                                          
         
        JFileChooser fc=new JFileChooser();
         
        fc.setDialogTitle("Elige un fichero");
         
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
         
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.txt", "txt");
        fc.setFileFilter(filtro);
         
        int eleccion=fc.showSaveDialog(this);
        if(eleccion==JFileChooser.APPROVE_OPTION){
            txtRuta.setText(fc.getSelectedFile().getPath());
        }
         
    }                                         
 
  
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verRuta().setVisible(true);
            }
        });
    }
 
    private javax.swing.JButton btnElegir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRuta;
}
